# Generated by Django 5.2.4 on 2025-08-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userincome", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="source",
            old_name="name",
            new_name="source",
        ),
    ]
